### ISSUE TITLE
PA Review: Playlist CRUD

### ISSUE THREAD

**Issue by khan-c** [khan-c/PlayThis#4]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by khan-c** [comment]
Seemed to run into an issue with my images (something to do with seeding data with images with paperclip. Will fix tomorrow morning. Should be an easy fix since I didn't really need paperclip since users won't be uploading their own playlist or artist images. May ultimately allow users to upload their own profile images given time.

**Comment by AAlfarho** [comment]
Great job with the playlist CRUD.
The look and feel and navigation feel natural, like the hover size change on the play button on the show playlist, kudos!

Just a couple of small details.
+ In the playlist show component, if I click delete and then cancel it stays in the same show component, but if I use the `esc` key instead of staying in the show component, I'm redirected to the browse component.
+ Once I create a playlist, is there a way to update the title?
+ The browse component seems to have a lot of extra horizontal space to the right, if we are not expecting a new component to take that space, could we center the display of the playlists.

**Comment by khan-c** [comment]
+ That's odd, I'm not seeing the bug regarding `esc` out of show component.
+ At the moment there is no way to update the title (spotify web player actually doesn't have this functionality either...). Given time, a bonus feature to add would be a click to edit on the playlist title in the playlist show page.
+ the horizontal space on the right is currently due to the sizing. At a certain size, it displays centered, but at a smaller width it displays this way. I will look into cleaning that up.

**Comment by khan-c** [comment]
I've gone ahead and centered the browse playlists.

**Comment by AAlfarho** [comment]
Great job, MVP completed.
